export const categories = [
  { id: 1, category: 'Animals' },
  { id: 2, category: 'Art' },
  { id: 3, category: 'Family' },
  { id: 4, category: 'Comedy' },
  { id: 5, category: 'Traveling' },
  { id: 6, category: 'Friendship' },
  { id: 7, category: 'Text' },
  { id: 8, category: 'Design' },
  { id: 9, category: 'Fashion' },
  { id: 10, category: 'Gaming' },
  { id: 11, category: 'Sports' },
  { id: 12, category: 'Social Media' },
  { id: 13, category: 'Auto&Vehicle' },
  { id: 14, category: 'Texe' },
  { id: 15, category: 'Career' },
  { id: 16, category: 'Education' },
  { id: 17, category: 'Relationship' },
  { id: 18, category: 'Reading' },
  { id: 19, category: 'Learning' },
  { id: 20, category: 'Food' },
];
