export const countries = [
  { label: 'Ukraine', code: 'UA' },
  { label: 'Italy', code: 'IT' },
  { label: 'United States of America', code: 'US' },
  { label: '1', code: 'UA' },
  { label: '2', code: 'UA' },
  { label: '3', code: 'UA' },
  { label: '4', code: 'GR' },
  { label: '5', code: 'UA' },
  { label: '6', code: 'UA' },
  { label: '7', code: 'UA' },
  { label: '8', code: 'UA' },
  { label: '9', code: 'UA' },
  { label: '10', code: 'UA' },
  { label: '11', code: 'UA' },
  { label: '12', code: 'UA' },
  { label: '13', code: 'UA' },
  { label: '14', code: 'UA' },
  { label: '15', code: 'UA' },
];
